[build]
  command = "npm run build"
  publish = ".next"
  
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Configurer le timeout des fonctions à 30 secondes (au lieu des 10 secondes par défaut)
[functions]
  included_files = ["node_modules/esbuild/**/*"]
  node_bundler = "esbuild"
  external_node_modules = ["openai"]
  timeout = 30

# Redirections
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 